/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/

'use strict';

var obsidian = require('obsidian');

class SnippetCommandsPlugin extends obsidian.Plugin {
    onload() {
        this.enableCommands();
    }
    onunload() {
    }
    reloadCommands() {
        this.unload();
        this.load();
    }
    enableCommands() {
        const customCss = this.app.customCss;
        const knownSnippets = customCss.snippets;
        console.log(`[Snippet Commands]: Loading commands for ${knownSnippets.length} snippets`, knownSnippets);
        knownSnippets.forEach((snippet) => {
            this.addCommand({
                id: `snippet-command-${snippet}`,
                name: `Toggle ${snippet}`,
                callback: () => {
                    customCss.setCssEnabledStatus(snippet, !customCss.enabledSnippets.has(snippet));
                }
            });
        });
        this.addCommand({
            id: `snippet-command-reload-all-snippets`,
            name: `Reload snippet commands`,
            callback: () => {
                this.reloadCommands();
            }
        });
    }
}

module.exports = SnippetCommandsPlugin;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoibWFpbi5qcyIsInNvdXJjZXMiOlsibWFpbi50cyJdLCJzb3VyY2VzQ29udGVudCI6bnVsbCwibmFtZXMiOlsiUGx1Z2luIl0sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7TUFFcUIscUJBQXNCLFNBQVFBLGVBQU07SUFFdkQsTUFBTTtRQUNKLElBQUksQ0FBQyxjQUFjLEVBQUUsQ0FBQztLQUN2QjtJQUVELFFBQVE7S0FDUDtJQUVELGNBQWM7UUFDWixJQUFJLENBQUMsTUFBTSxFQUFFLENBQUE7UUFDYixJQUFJLENBQUMsSUFBSSxFQUFFLENBQUM7S0FDYjtJQUVELGNBQWM7UUFDWixNQUFNLFNBQVMsR0FBSSxJQUFJLENBQUMsR0FBVyxDQUFDLFNBQVMsQ0FBQztRQUM5QyxNQUFNLGFBQWEsR0FBRyxTQUFTLENBQUMsUUFBUSxDQUFDO1FBQ3pDLE9BQU8sQ0FBQyxHQUFHLENBQUMsNENBQTRDLGFBQWEsQ0FBQyxNQUFNLFdBQVcsRUFBRSxhQUFhLENBQUMsQ0FBQztRQUN4RyxhQUFhLENBQUMsT0FBTyxDQUFDLENBQUMsT0FBYztZQUNuQyxJQUFJLENBQUMsVUFBVSxDQUFDO2dCQUNkLEVBQUUsRUFBRSxtQkFBbUIsT0FBTyxFQUFFO2dCQUNoQyxJQUFJLEVBQUUsVUFBVSxPQUFPLEVBQUU7Z0JBQ3pCLFFBQVEsRUFBRTtvQkFDUixTQUFTLENBQUMsbUJBQW1CLENBQUMsT0FBTyxFQUFFLENBQUMsU0FBUyxDQUFDLGVBQWUsQ0FBQyxHQUFHLENBQUMsT0FBTyxDQUFDLENBQUMsQ0FBQztpQkFDakY7YUFDRixDQUFDLENBQUM7U0FDSixDQUFDLENBQUM7UUFDSCxJQUFJLENBQUMsVUFBVSxDQUFDO1lBQ2QsRUFBRSxFQUFFLHFDQUFxQztZQUN6QyxJQUFJLEVBQUUseUJBQXlCO1lBQy9CLFFBQVEsRUFBRTtnQkFDUixJQUFJLENBQUMsY0FBYyxFQUFFLENBQUM7YUFDdkI7U0FDRixDQUFDLENBQUM7S0FDSjs7Ozs7In0=
