site_name: Chen's LMS
repo_url: https://github.com/laozhou-in-germany/Chens_LMS_Public/
edit_uri: blob/main/docs/docs/

nav:
    - Quick Start:
        - User Interface: qs01_ui.md
        - Use Goal Management: qs11_use_goal_management.md
        - Use Journal: qs12_use_journal.md
        - Use Knowledge Management: qs13_use_knowledge_management.md
        - Use Periodic Review: qs14_use_periodic_review.md
    - Showcase:
        - Goal Management: sc_goal_management.md
        - Journal: sc_journal.md
        - Knowledge Management: sc_knowledge_management.md
        - Periodic Reviews: sc_periodic_review.md
    - Reference: ref0_general.md
    - About: about.md
    - 中文帮助:  en_cn.md
markdown_extensions:
  - footnotes
  - admonition