site_name: Chen's LMS
repo_url: https://github.com/laozhou-in-germany/Chens_LMS_Public/
edit_uri: blob/main/docs/docs/

nav:
    - Intro: index.md
    - Quick Start: quick_start.md
    - Showcase: showcase.md
    - Reference: reference.md
    - About: about.md
    - 中文帮助:  en_cn.md
markdown_extensions:
  - footnotes